# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-nist-si-4-mkdir-bin-dir
  namespace: default # Change your namespace
spec:
  tags: ["NIST", "NIST_800-53_AU-2", "NIST_800-53_SI-4" , "MITRE", "MITRE_T1036_masquerading"]
  message: "Alert! An attempt to write below system binary directories denied."
  selector:
    matchLabels:
      app: nginx-test    #change this label with your label
  severity: 5
  file:
    matchDirectories:
    - dir: /bin/
      recursive: true
      readOnly: true
    - dir: /sbin/
      recursive: true
      readOnly: true
    - dir: /usr/sbin/
      recursive: true
      readOnly: true
    - dir: /usr/bin/
      recursive: true
      readOnly: true
  action: Block