apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: restrict-automount-sa-token
  namespace: default
spec:
  validationFailureAction: audit
  background: true
  rules:
    - name: validate-automountServiceAccountToken
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{ request.operation || 'BACKGROUND' }}"
            operator: NotEquals
            value: DELETE
      validate:
        message: "Auto-mounting of Service Account tokens is not allowed."
        pattern:
          spec:
            automountServiceAccountToken: "false"
