# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-restrict-access-to-mysqldump
  namespace: default # Change your namespace
spec:
  tags: ["MySQL", "mysqldump","process"]
  message: "Alert! mysqldump command execution detected."
  selector:
    matchLabels:
      app: mysql # Change your labels
  severity: 10
  process:
    matchPaths:
    - path: /usr/bin/mysqldump
  action: Audit